# Generated by Django 2.2.5 on 2019-10-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
