# Generated by Django 2.2.5 on 2019-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20191028_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='img', verbose_name='Картинка_1')),
                ('image_2', models.ImageField(blank=True, upload_to='img', verbose_name='Картинка_2')),
                ('image_3', models.ImageField(blank=True, upload_to='img', verbose_name='Картинка_3')),
                ('image_4', models.ImageField(blank=True, upload_to='img', verbose_name='Картинка_4')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'акцию',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'информацb.', 'verbose_name_plural': 'О нас'},
        ),
    ]
