# Generated by Django 2.2.5 on 2019-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20191029_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Доставка/оплата')),
            ],
            options={
                'verbose_name_plural': 'Доставка/оплата',
                'verbose_name': 'информацию',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'информацию', 'verbose_name_plural': 'О нас'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image_4',
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/image', verbose_name='Картинка'),
        ),
    ]
