# Generated by Django 2.2.5 on 2019-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20191031_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price_3',
            field=models.CharField(max_length=25, verbose_name='Цена от 50 до 100'),
        ),
        migrations.AlterField(
            model_name='box',
            name='price_4',
            field=models.CharField(max_length=25, verbose_name='Цена от 101'),
        ),
    ]
