# Generated by Django 2.2.5 on 2019-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_auto_20191031_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='media/image', verbose_name='Картинка 1')),
                ('image_2', models.ImageField(upload_to='media/image', verbose_name='Картинка 2')),
                ('image_3', models.ImageField(upload_to='media/image', verbose_name='Картинка 3')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('size', models.CharField(max_length=25, verbose_name='Габариты')),
                ('price_1', models.CharField(max_length=25, verbose_name='Цена от 1 до 10')),
                ('price_2', models.CharField(max_length=25, verbose_name='Цена от 11 до 50')),
                ('price_3', models.CharField(max_length=25, verbose_name='Цена от 50 до 100')),
                ('price_4', models.CharField(max_length=25, verbose_name='Цена от 101')),
            ],
            options={
                'verbose_name': 'коробку',
                'verbose_name_plural': 'Коробки_колонка_1',
            },
        ),
        migrations.CreateModel(
            name='Box_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='media/image', verbose_name='Картинка 1')),
                ('image_2', models.ImageField(upload_to='media/image', verbose_name='Картинка 2')),
                ('image_3', models.ImageField(upload_to='media/image', verbose_name='Картинка 3')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('size', models.CharField(max_length=25, verbose_name='Габариты')),
                ('price_1', models.CharField(max_length=25, verbose_name='Цена от 1 до 10')),
                ('price_2', models.CharField(max_length=25, verbose_name='Цена от 11 до 50')),
                ('price_3', models.CharField(max_length=25, verbose_name='Цена от 50 до 100')),
                ('price_4', models.CharField(max_length=25, verbose_name='Цена от 101')),
            ],
            options={
                'verbose_name': 'коробку',
                'verbose_name_plural': 'Коробки_колонка_1',
            },
        ),
        migrations.CreateModel(
            name='Box_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='media/image', verbose_name='Картинка 1')),
                ('image_2', models.ImageField(upload_to='media/image', verbose_name='Картинка 2')),
                ('image_3', models.ImageField(upload_to='media/image', verbose_name='Картинка 3')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('size', models.CharField(max_length=25, verbose_name='Габариты')),
                ('price_1', models.CharField(max_length=25, verbose_name='Цена от 1 до 10')),
                ('price_2', models.CharField(max_length=25, verbose_name='Цена от 11 до 50')),
                ('price_3', models.CharField(max_length=25, verbose_name='Цена от 50 до 100')),
                ('price_4', models.CharField(max_length=25, verbose_name='Цена от 101')),
            ],
            options={
                'verbose_name': 'коробку',
                'verbose_name_plural': 'Коробки_колонка_3',
            },
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='media/image', verbose_name='Картинка'),
        ),
    ]
